### ISSUE TITLE
Possible false positives in mesh_booleans_inputcheck

### ISSUE THREAD

**Issue by kunitsyn** [gcherchi/InteractiveAndRobustMeshBooleans#12]
Hello, thank you for this great work. This mesh (OBJ format):
```
v 1 0 1
v 0 0 0
v 1.3 0.5 1.1
v 1 1 2
v 1.4 0.5 2
v 1 0 2
f 1 2 3
f 2 4 3
f 4 2 5
f 2 6 5
f 5 6 3
f 6 1 3
f 6 2 1
f 4 5 3
```
doesn't pass the mesh_booleans_inputcheck check with a "your input is not well oriented" error. Additionally, this mesh:
```
v 1 0 1
v 0 0 0
v 1.3 0.5 1
v 1 1 2
v 1.4 0.5 2
v 1 0 2
f 1 2 3
f 2 4 3
f 4 2 5
f 2 6 5
f 5 6 3
f 6 1 3
f 6 2 1
f 4 5 3
```
(the only difference is in the third line) fails with "this should not be happening". This happens on both latest main and octree_cinolib branches.

But both these meshes look okay to me; they are manifold and all their triangles look outside. Maybe I don't get something?

**Comment by mlivesu** [comment]
Thanks for your detailed examples. It may be a bug. I'll look into that and get back to you asap

**Comment by mlivesu** [comment]
there is a point that is not clear to me. For the second model that you shared, which program is failing? Is it the input checker or the actual boolean? If the latter, what type of boolean are you computing? And with what other model? We need to be able to reproduce your same issue
thanks!

**Comment by kunitsyn** [comment]
For the second model, the input checker is failing.

**Comment by starseeker** [comment]
I'm getting a build error with latest main:

```
main-inputcheck.cpp:47:14: error: ‘const class cinolib::Trimesh<>’ has no member named ‘mesh_is_manifold’; did you mean ‘vert_is_manifold’?
   47 |     return m.mesh_is_manifold();
      |              ^~~~~~~~~~~~~~~~
      |              vert_is_manifold
```

**Comment by mlivesu** [comment]
ops, my bad. The version of cinolib inside this project is not up to date.
Can you try again please?

**Comment by starseeker** [comment]
Building again - thanks!

**Comment by kunitsyn** [comment]
Thank you, @mlivesu, it works now.

**Comment by mlivesu** [comment]
Thank you for spotting this bug.

Just a minor thing: in its current form the check on the outward orientation of triangle normals assumes that the input mesh is a single connected component. If this is not the case that check becomes unreliable. It is easy to extend that check to multiply connected components, but I was lazy today :)
I'll generalize it in the following days
