### ISSUE TITLE
some non-manifold and naked edges after subtraction

### ISSUE THREAD

**Issue by rob-rb** [gcherchi/InteractiveAndRobustMeshBooleans#14]
Example inputs:

mesh_booleans subtraction input1.obj input2.obj output.obj
[problem.zip](https://github.com/gcherchi/InteractiveAndRobustMeshBooleans/files/11097721/problem.zip)

Is there maybe a workaround in preparing the meshes, like projecting vertices of input2.obj which are near input1.obj to input1.obj?

**Comment by mlivesu** [comment]
sorry this is a period dense of many commitments, we'll be back after the SGP deadline (mid April).
Meanwhile, you may want to write a bit more about your issue. Reading the message it's not clear what's your request
