### ISSUE TITLE
BUG: Compilation errors on Windows

### ISSUE THREAD

**Issue by mariuszhermansdorfer** [gcherchi/InteractiveAndRobustMeshBooleans#16]
Cloned repo doesn't compile on Windows 10 with Visual Studio 2022. 

It seems that @marcomanno has fixed it in [his fork](https://github.com/marcomanno/InteractiveAndRobustMeshBooleans/commit/b581f4aaef723d7d10609e8b2f9ca76848087957). 

Following these changes I was able to compile the library but keep running into #15 with all the demos (rotation, stencil etc.) and my own custom tests. 

@marcomanno - are you experiencing the same issues?

**Comment by gcherchi** [comment]
Dear Mariusz,
Thanks for the tip. We tested our code on Windows before releasing the code. Currently, we cannot test the code on Windows, so we prefer not to apply any changes.

**Comment by gcherchi** [comment]
One of our co-authors has been able to test the code on Windows. 
We are going to upload a fix shortly.

**Comment by mariuszhermansdorfer** [comment]
Thanks. On my machine, I had to apply the fix from the fork and change the CMakeSettings as follows. The first configuration is the default one and it resulted in #15 also on the meshes shipping with the library. Switching to the second configuration made the bugs dissapear:

``` json
{
  "configurations": [
    {
      "name": "x64-Debug",
      "generator": "Ninja",
      "configurationType": "Debug",
      "inheritEnvironments": [ "msvc_x64_x64" ],
      "buildRoot": "${projectDir}\\out\\build\\${name}",
      "installRoot": "${projectDir}\\out\\install\\${name}",
      "cmakeCommandArgs": "",
      "buildCommandArgs": "",
      "ctestCommandArgs": ""
    },
    {
      "name": "x64-Release",
      "generator": "Visual Studio 17 2022 Win64",
      "configurationType": "Release",
      "inheritEnvironments": [ "msvc_x64" ],
      "buildRoot": "${projectDir}\\out\\build\\${name}",
      "installRoot": "${projectDir}\\out\\install\\${name}",
      "cmakeCommandArgs": "",
      "buildCommandArgs": "",
      "ctestCommandArgs": ""
    }
  ]
}
```

**Comment by mariuszhermansdorfer** [comment]
I can confirm that https://github.com/gcherchi/InteractiveAndRobustMeshBooleans/commit/7081647a8cc7cc823015044964cd071767947f66 fixes the issue.
