### ISSUE TITLE
Inconsistencies with pointy meshes

### ISSUE THREAD

**Issue by mariuszhermansdorfer** [gcherchi/InteractiveAndRobustMeshBooleans#17]
Having solved the compilation issues from #16, I was able to perform some tests with various types of geometries. First of all, congrats on putting together this work! It really is a pleasant experience to work with boolean operations in such an interactive way!

Most geometries work without issues:

https://user-images.githubusercontent.com/49192999/233772825-0cc990b7-9f92-4813-a9c7-166d4484644c.mp4

There are, however, some inconsistencies with pointy meshes where multiple faces meet at one vertex. Interestingly, these are most visible with the union operation, while intersect and subtraction work well for the same inputs:

https://user-images.githubusercontent.com/49192999/233772914-39900876-acba-409c-922a-f5072a00d2c0.mp4

Is this expected behavior?

**Comment by gcherchi** [comment]
Dear Mariusz,
From the video I can't see what the problem is. It seems to me that all the results are correct. 
Please send me the models in the exact position where you produce the result you think is incorrect.
As soon as I have some time I'll try to check them.

**Comment by mariuszhermansdorfer** [comment]
Dear Gianmarco,

thanks for offering to look into this issue. 
Here is a specific case, where the Subtraction operation works correctly, but Union and Intersection fail:
![image](https://user-images.githubusercontent.com/49192999/234807292-7c0fd894-ab8b-4293-8143-cb3c63d50a72.png)

[Obj.zip](https://github.com/gcherchi/InteractiveAndRobustMeshBooleans/files/11341377/Obj.zip)

**Comment by gcherchi** [comment]
Dear Mariusz,
I tested your models and all Boolean operations work fine. [Here](https://github.com/gcherchi/InteractiveAndRobustMeshBooleans/files/11341875/results.zip) a zip with my results.

**Comment by mariuszhermansdorfer** [comment]
Thanks for checking. I'll have to investigate what happens on my end of the pipeline then.
