### ISSUE TITLE
The mempool crashed when mesh have selfintersection

### ISSUE THREAD

**Issue by GridGeneration** [gcherchi/InteractiveAndRobustMeshBooleans#32]

**Comment by gcherchi** [comment]
Yes, it's normal. One of the requirements of our code is that the input must be self-intersection free (see the Readme).
<img width="848" alt="Screenshot 2024-01-11 alle 09 17 51" src="https://github.com/gcherchi/InteractiveAndRobustMeshBooleans/assets/14749123/8a22d2ed-05b9-495b-b428-8297665d7d4b">
