### ISSUE TITLE
Incorrect orientation of output triangles from subtraction (and xor)?

### ISSUE THREAD

**Issue by Omsala** [gcherchi/InteractiveAndRobustMeshBooleans#4]
It seems the triangles in the output from a subtraction operation corresonding to the surface of the second mesh are incorrectly being returned with their original orientation. Should they not have their orientation reversed? Otherwise the output mesh doesn't have a consistent normal direction. A similar issue seems to apply to XOR as well.

**Comment by gcherchi** [comment]
Dear Omsala,
Thank you for your interest inn our work.
You're totally right. I just committed a fix for the triangles orientation.
